server:
  port: 8001


aes:
  key: devh

jwt:
  auth:
    issuer: devh
    secretKey: devh
    accessExpire: 3600
    refreshExpire: 604800
    header: Authorization

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/devh?rewriteBatchedStatements=true
    username: devh
    password: J6zXTGI6Fxtnzkd7wb26Jm0Pddmp0+vAZ8835vfPVCGncZyLLEfpT83ZMEGGwB9a60I5Yw==
  sql:
    init:
      platform: mariadb
      schema-locations: classpath*:db/schema-${spring.sql.init.platform}.sql
      data-locations: classpath*:db/data-${spring.sql.init.platform}.sql
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: false

logging:
  config: classpath:log4j2.xml
